chore: add sticky settings variables
equinor/terraform-azurerm-function-app pull request #76
Opened 2024-10-09 13:55 UTC by sebastianlolv

### Checklist

- [x] I've updated both the `azurerm_linux_function_app` and `azurerm_windows_function_app` resources.

2024-10-09 14:06 UTC, sebastianlolv commented
Doesn't look like sticky settings can be empty 🤔

2025-01-29 09:59 UTC, kov117 commented
I will be taking over this PR since i need this for another project.

2025-01-30 10:00 UTC, hknutsen requested changes
I think this looks good 🎉 

Requested a couple of nitpicky changes.

2025-01-30 10:00 UTC, hknutsen commented on tests/configuration.unit.tftest.hcl
> +run "linux_sticky_settings__connection_string_names_filled" {
Remove duplicate `_`:

```suggestion
run "linux_sticky_settings_connection_string_names_filled" {
```

2025-01-30 10:00 UTC, hknutsen commented on main.tf
> +    for_each = length(var.sticky_settings_app_setting_names) > 0 || length(var.sticky_settings_connection_string_names) > 0 ? [""] : []
Which value we put here isn't important, what's important is that there's a **single** value in this list, however we usually put `0` so I suggest we change to that to stay consistent.

```suggestion
    for_each = length(var.sticky_settings_app_setting_names) > 0 || length(var.sticky_settings_connection_string_names) > 0 ? [0] : []
```

2025-01-30 10:00 UTC, hknutsen commented on main.tf
> +    for_each = length(var.sticky_settings_app_setting_names) > 0 || length(var.sticky_settings_connection_string_names) > 0 ? [""] : []
Same as previous:

```suggestion
    for_each = length(var.sticky_settings_app_setting_names) > 0 || length(var.sticky_settings_connection_string_names) > 0 ? [0] : []
```

2025-01-30 10:47 UTC, hknutsen approved these changes

2025-01-30 10:48 UTC, merged