feat: configure ftps state
equinor/terraform-azurerm-function-app pull request #81
Opened 2024-11-21 14:00 UTC by kov117

### Checklist

- [x] I've updated both the `azurerm_linux_function_app` and `azurerm_windows_function_app` resources.

Test passed 🎆  

But i have a question for @equinor/terraform-baseline-maintainers, according to this [FTPS](https://learn.microsoft.com/en-us/azure/app-service/deploy-ftp?tabs=portal#enforce-ftps) we can just disable (as i have it by default) both FTP and FTPS if we are not using FTP deployment. But if we want enchanced security, we should allow FTP over TLS/SSL. Do you guys have any thoughs about this ?

2024-11-21 14:19 UTC, hknutsen requested changes

2024-11-21 14:19 UTC, hknutsen commented on variables.tf
> +  description = "State of FTP/FTPS service for this Windows Function App."
Phrasing and allowed values (according to [variable descriptions best practices](https://equinor.github.io/terraform-baseline/best-practices/variables-and-outputs/#variable-and-output-descriptions)):

```suggestion
  description = "The state of the FTP / FTPS service for this Function App. Value must be \"AllAllowed\", \"FtpsOnly\" or \"Disabled\"."
```

2024-11-21 14:22 UTC, hknutsen requested changes

2024-11-21 14:22 UTC, hknutsen commented on variables.tf
> +}
Validate allowed values (according to [best practices](https://equinor.github.io/terraform-baseline/best-practices/variables-and-outputs/)):

```suggestion
  default     = "Disabled"
  
  validation {
    condition     = contains(["AllAllowed", "FtpsOnly", "Disabled"], var.ftps_state)
    error_message = "FTPS state must be \"AllAllowed\", \"FtpsOnly\" or \"Disabled\"."
  }
}
```

2024-11-22 08:37 UTC, kov117 commented
Ran new test and it passed 👍🏼

2024-11-26 06:40 UTC, kov117 commented
Terraform test passed 👍🏼

2024-11-26 07:57 UTC, hknutsen approved these changes
Looks good 👍

2024-11-26 07:57 UTC, merged