feat: configure the http2 protocol
equinor/terraform-azurerm-function-app pull request #82
Opened 2024-11-22 06:22 UTC by kov117

### Checklist

- [x] I've updated both the `azurerm_linux_function_app` and `azurerm_windows_function_app` resources.

2024-11-22 06:23 UTC, kov117 commented
Test pass 🎆

2024-11-25 10:47 UTC, hknutsen requested changes

2024-11-25 10:47 UTC, hknutsen commented on variables.tf
> +  description = "Specifies if the HTTP2 protocol should be enabled."
Make description more similar to existing variables:

```suggestion
  description = "Should the HTTP2 protocol be enabled for this Function App?"
```

2024-11-25 11:44 UTC, kov117 commented
Test passed 👍🏼

2024-11-25 12:49 UTC, hknutsen requested changes

2024-11-25 12:49 UTC, hknutsen commented on tests/configuration.unit.tftest.hcl
> +    condition = azurerm_linux_function_app.this[0].site_config[0].http2_enabled == false
Typo:

```suggestion
    condition = azurerm_windows_function_app.this[0].site_config[0].http2_enabled == false
```

2024-11-25 12:49 UTC, hknutsen commented on tests/configuration.unit.tftest.hcl
> +    condition = azurerm_linux_function_app.this[0].site_config[0].http2_enabled == true
Typo:

```suggestion
    condition = azurerm_windows_function_app.this[0].site_config[0].http2_enabled == true
```

2024-11-26 06:46 UTC, kov117 commented
Terraform test passed 👍🏼

2024-11-26 09:04 UTC, hknutsen approved these changes
Looks good 👍

2024-11-26 09:04 UTC, merged